# fly.toml file generated for gitcloud-actions on 2022-08-04T10:14:08-05:00

app = "gitcloud-actions"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PRODUCTION = 1
OTEL_EXPORTER_OTLP_ENDPOINT = "https://api.honeycomb.io"
OTEL_SERVICE_NAME = "gitcloud-actions"

[build]
builder = "heroku/buildpacks:20"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 5001
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
