name: Test Oso Cloud Policies
on: [push]

jobs:
  install_oso_cloud_cli:
    runs-on: ubuntu-latest
    name: Validate policy syntax and logic
    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v4
      - name: Install the CLI
        id: install-cli
        uses: gsarjeant/install-oso-cloud-tools@releases/v1