name: Test Oso Cloud Policies
on: [push]

jobs:
  install_oso_cloud_cli:
    runs-on: ubuntu-latest
    name: Validate policy syntax and logic
    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v2
      - name: Install the CLI
        id: install-cli
        uses: ./.github/actions/oso/install-oso-cloud-cli
      - name: Install the local binary
        id: install-local-binary
        uses: ./.github/actions/oso/install-oso-cloud-local-binary
      - name: Get the installed version
        run: echo "The version was ${{ steps.install.outputs.version }}"
