name: Test Oso Cloud Policies
on: [push]

jobs:
  validate-polar-syntax:
    runs-on: ubuntu-latest
    name: Validate policy syntax and logic
    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v4
      - name: Install the Oso Cloud Tools
        id: install-oso-cloud-tools
        uses: gsarjeant/install-oso-cloud-tools@main
      - name: Report installed CLI Version
        id: report-cli-version
        run: echo "Installed CLI version ${{ steps.install-oso-cloud-tools.outputs.cli-version }}, sha ${{ steps.install-oso-cloud-tools.outputs.cli-sha }}"
      - name: Validate Polar Syntax
        id: validate-polar-syntax
        uses: gsarjeant/validate-polar-syntax@releases/v1