on: [push]

jobs:
  install_oso_cloud_cli:
    runs-on: ubuntu-latest
    name: Install the latest version of the OSO Cloud CLI
    steps:
      - name: Install CLI
        id: install
        uses: ../actions/oso-cloud
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The version was ${{ steps.install.outputs.version }}"
