name: Test Oso Cloud Policies
on: [push]

jobs:
  validate-polar:
    runs-on: ubuntu-latest
    name: Validate policy syntax and logic
    env:
      OSO_AUTH: ${{ secrets.OSO_CLOUD_API_KEY }}
    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v4
      - name: Install the Oso Cloud Tools
        id: install-oso-cloud-tools
        uses: gsarjeant/install-oso-cloud-tools@main
      - name: Report installed CLI Version
        id: report-cli-version
        run: echo "Installed CLI version ${{ steps.install-oso-cloud-tools.outputs.cli-version }}, sha ${{ steps.install-oso-cloud-tools.outputs.cli-sha }}"
      - name: Validate Polar Syntax
        id: validate-polar-syntax
        uses: gsarjeant/validate-polar-syntax@releases/v1
      - name: Run Polar Tests
        id: run-polar-tests
        uses: gsarjeant/run-polar-tests@releases/v1
